/** Hand-drawn illustrated scene layer for the doc engine (2026-07-19).
 *
 *  The anti-"AI slop" brand look: Gemini illustrations in ONE locked ink style
 *  (scripts/gen_mascot.py STYLE) rendered on textured paper with a marker-style
 *  draw-on reveal, subtle line boil, handwritten captions (Caveat), and the
 *  recurring mascot reacting in the corner (public/mascot/<pose>.png,
 *  generated by scripts/gen_mascot.py — the channel's face).
 *
 *  Scene fields (DocWide): sketch:true + img:<prefix> -> SketchScene;
 *  react:<pose> overlays the mascot on ANY scene type.
 */
import React from "react";
import {
  AbsoluteFill, Img, interpolate, spring, staticFile, useCurrentFrame,
} from "remotion";
import { SKETCH_FONT_CSS } from "./sketchFonts";

const FPS = 30;
const PAPER = "#F4F0E6";
const INK = "#1C1A17";

/* deterministic rng (Remotion rule: no bare Math.random) */
const mulberry32 = (a: number) => () => {
  a |= 0; a = (a + 0x6d2b79f5) | 0;
  let t = Math.imul(a ^ (a >>> 15), 1 | a);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const seedOf = (s: string) => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
};

/** Thick boustrophedon scribble path covering a box — used as a mask stroke so
 *  the illustration appears where the "marker" has passed. */
const scribblePath = (w: number, h: number, bands: number, seed: number) => {
  const rng = mulberry32(seed);
  const bh = h / bands;
  let d = `M ${-w * 0.05} ${bh / 2}`;
  for (let i = 0; i < bands; i++) {
    const y = bh * i + bh / 2;
    const wob = () => (rng() - 0.5) * bh * 0.5;
    if (i % 2 === 0) {
      d += ` C ${w * 0.3} ${y + wob()}, ${w * 0.7} ${y + wob()}, ${w * 1.05} ${y}`;
    } else {
      d += ` C ${w * 0.7} ${y + wob()}, ${w * 0.3} ${y + wob()}, ${-w * 0.05} ${y}`;
    }
    if (i < bands - 1) {
      const xEnd = i % 2 === 0 ? w * 1.05 : -w * 0.05;
      d += ` C ${xEnd} ${y + bh * 0.6}, ${xEnd} ${y + bh * 0.9}, ${xEnd} ${y + bh}`;
    }
  }
  return d;
};

/** Paper background: warm tone + procedural grain + soft vignette. */
export const Paper: React.FC = () => (
  <AbsoluteFill style={{ background: PAPER }}>
    <svg width="100%" height="100%" style={{ position: "absolute", opacity: 0.5 }}>
      <filter id="paperGrain">
        <feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves={2} seed={7} />
        <feColorMatrix type="matrix"
          values="0 0 0 0 0.55  0 0 0 0 0.52  0 0 0 0 0.46  0 0 0 0.06 0" />
      </filter>
      <rect width="100%" height="100%" filter="url(#paperGrain)" />
    </svg>
    <AbsoluteFill style={{
      background: "radial-gradient(ellipse at center, transparent 58%, rgba(60,50,30,0.14) 100%)",
    }} />
  </AbsoluteFill>
);

/** The mascot popping into a corner and idling — the brand's face reacting.
 *  pose = file stem under public/mascot/. Works over ANY scene type. */
export const MascotReact: React.FC<{ pose: string; sceneDur: number }> = ({ pose, sceneDur }) => {
  const frame = useCurrentFrame();
  const pop = spring({ frame: frame - 4, fps: FPS, config: { damping: 11, stiffness: 140 } });
  const out = interpolate(frame, [sceneDur - 8, sceneDur - 2], [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  // idle quantized ON THREES (~10fps) + seeded per-step jitter: a hand-drawn
  // character "boils" in place — smooth sinusoid glide reads as digital
  const step = Math.floor(frame / 3);
  const jit = mulberry32(seedOf(pose) + step);
  const bob = Math.sin(step / 3.6) * 6 + (jit() - 0.5) * 2;
  const tilt = Math.sin(step / 5.6) * 1.6 + (jit() - 0.5) * 0.8;
  return (
    <div style={{
      position: "absolute", right: 44, bottom: 30, width: 320, height: 340,
      transform: `scale(${pop * out}) translateY(${bob}px) rotate(${-3 + tilt}deg)`,
      transformOrigin: "bottom right",
    }}>
      <Img
        src={staticFile(`mascot/${pose}.png`)}
        style={{
          width: "100%", height: "100%", objectFit: "contain",
          filter: "drop-shadow(3px 5px 0px rgba(28,26,23,0.18))",
        }}
      />
    </div>
  );
};

type SketchProps = {
  file: string | null;      // resolved illustration filename (img rotation)
  slug: string;
  cap?: string;
  stat?: string;
  note?: string;            // small handwritten margin annotation
  accent: string;           // channel accent color
  sceneDur: number;
};

export const SketchScene: React.FC<SketchProps> = ({
  file, slug, cap, stat, note, accent, sceneDur,
}) => {
  const frame = useCurrentFrame();
  const seed = seedOf(`${slug}:${file ?? "none"}`);
  // line boil ON THREES (~10fps, the hand-animation cadence): cycle turbulence
  // seeds so the static art's line quivers like ink — a frozen drawing is the
  // "digital" tell, per the style research
  const boilSeed = (seed % 90) + Math.floor(frame / 3) % 3;

  const W = 1180, H = 760;
  const bands = 9;
  const path = scribblePath(W, H, bands, seed);
  // draw-on: marker covers the art in ~0.9s, eased like a real hand (fast
  // middle, settling end)
  const reveal = interpolate(frame, [2, 30], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const dashLen = W * bands * 1.35;

  const capIn = interpolate(frame, [16, 34], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const underline = interpolate(frame, [30, 48], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const statPop = spring({ frame: frame - 24, fps: FPS, config: { damping: 10, stiffness: 130 } });
  const drift = interpolate(frame, [0, Math.max(sceneDur, 1)], [0, -10]);

  return (
    <AbsoluteFill>
      <style>{SKETCH_FONT_CSS}</style>
      <Paper />
      {file && (
        <div style={{
          position: "absolute", left: "50%", top: 78,
          transform: `translateX(-50%) translateY(${-drift}px) rotate(-0.6deg)`,
        }}>
          <svg width={W} height={H}>
            <defs>
              <filter id="boil" x="-4%" y="-4%" width="108%" height="108%">
                <feTurbulence type="turbulence" baseFrequency="0.022" numOctaves={2}
                  seed={boilSeed} result="t" />
                <feDisplacementMap in="SourceGraphic" in2="t" scale={6}
                  xChannelSelector="R" yChannelSelector="G" />
              </filter>
              <mask id="reveal">
                <path d={path} stroke="#fff" strokeWidth={H / bands + 14} fill="none"
                  strokeLinecap="round"
                  strokeDasharray={dashLen}
                  strokeDashoffset={dashLen * (1 - reveal)} />
              </mask>
            </defs>
            {/* illustrations are white->alpha preprocessed (gen_mascot.white_to_alpha)
                so real transparency sits on the paper — no blend-mode tricks */}
            <g mask="url(#reveal)">
              <image
                href={staticFile(`shorts/${slug}/images/${file}`)}
                width={W} height={H} preserveAspectRatio="xMidYMid meet"
                filter="url(#boil)"
              />
            </g>
          </svg>
        </div>
      )}

      {stat && (
        <div style={{
          position: "absolute", left: 64, top: 44,
          transform: `scale(${statPop}) rotate(-2deg)`, transformOrigin: "top left",
          fontFamily: "'Caveat', cursive", fontWeight: 700, fontSize: 74,
          color: accent, textShadow: "1px 2px 0 rgba(28,26,23,0.15)",
        }}>
          {stat}
        </div>
      )}

      {cap && (
        <div style={{
          position: "absolute", left: 84, bottom: 64, maxWidth: 1100,
          opacity: capIn, transform: `translateY(${(1 - capIn) * 14}px) rotate(-1.1deg)`,
        }}>
          <div style={{
            fontFamily: "'Caveat', cursive", fontWeight: 700,
            fontSize: 72, lineHeight: 1.05, color: INK,
          }}>
            {cap}
          </div>
          <svg width={520} height={16} style={{ display: "block", marginTop: 2 }}>
            <path d="M 4 9 C 120 4, 240 13, 380 8 C 440 6, 490 10, 514 8"
              stroke={accent} strokeWidth={6} fill="none" strokeLinecap="round"
              strokeDasharray={540} strokeDashoffset={540 * (1 - underline)} />
          </svg>
        </div>
      )}

      {note && (
        <div style={{
          position: "absolute", right: 70, top: 60, maxWidth: 360,
          opacity: capIn, transform: "rotate(2.4deg)",
          fontFamily: "'Patrick Hand', cursive", fontSize: 38, lineHeight: 1.15,
          color: "rgba(28,26,23,0.72)",
        }}>
          {note}
        </div>
      )}
    </AbsoluteFill>
  );
};
