/** Hand-drawn illustrated scene layer for the doc engine (2026-07-19).
 *
 *  The anti-"AI slop" brand look: Gemini illustrations in ONE locked ink style
 *  (scripts/gen_mascot.py STYLE) rendered on textured paper with a marker-style
 *  draw-on reveal, subtle line boil, handwritten captions (Caveat), and the
 *  recurring mascot reacting in the corner (public/mascot/<pose>.png,
 *  generated by scripts/gen_mascot.py — the channel's face).
 *
 *  Scene fields (DocWide): sketch:true + img:<prefix> -> SketchScene;
 *  react:<pose> overlays the mascot on ANY scene type.
 */
import React from "react";
import {
  AbsoluteFill, Img, interpolate, spring, staticFile, useCurrentFrame,
} from "remotion";
import { SKETCH_FONT_CSS } from "./sketchFonts";

const FPS = 30;
const PAPER = "#F4F0E6";
const INK = "#1C1A17";

/* deterministic rng (Remotion rule: no bare Math.random) */
const mulberry32 = (a: number) => () => {
  a |= 0; a = (a + 0x6d2b79f5) | 0;
  let t = Math.imul(a ^ (a >>> 15), 1 | a);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const seedOf = (s: string) => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
};

/** Thick boustrophedon scribble path covering a box — used as a mask stroke so
 *  the illustration appears where the "marker" has passed. */
const scribblePath = (w: number, h: number, bands: number, seed: number) => {
  const rng = mulberry32(seed);
  const bh = h / bands;
  let d = `M ${-w * 0.05} ${bh / 2}`;
  for (let i = 0; i < bands; i++) {
    const y = bh * i + bh / 2;
    const wob = () => (rng() - 0.5) * bh * 0.5;
    if (i % 2 === 0) {
      d += ` C ${w * 0.3} ${y + wob()}, ${w * 0.7} ${y + wob()}, ${w * 1.05} ${y}`;
    } else {
      d += ` C ${w * 0.7} ${y + wob()}, ${w * 0.3} ${y + wob()}, ${-w * 0.05} ${y}`;
    }
    if (i < bands - 1) {
      const xEnd = i % 2 === 0 ? w * 1.05 : -w * 0.05;
      d += ` C ${xEnd} ${y + bh * 0.6}, ${xEnd} ${y + bh * 0.9}, ${xEnd} ${y + bh}`;
    }
  }
  return d;
};

/** Paper background: warm tone + procedural grain + soft vignette. */
export const Paper: React.FC = () => (
  <AbsoluteFill style={{ background: PAPER }}>
    <svg width="100%" height="100%" style={{ position: "absolute", opacity: 0.5 }}>
      <filter id="paperGrain">
        <feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves={2} seed={7} />
        <feColorMatrix type="matrix"
          values="0 0 0 0 0.55  0 0 0 0 0.52  0 0 0 0 0.46  0 0 0 0.06 0" />
      </filter>
      <rect width="100%" height="100%" filter="url(#paperGrain)" />
    </svg>
    <AbsoluteFill style={{
      background: "radial-gradient(ellipse at center, transparent 58%, rgba(60,50,30,0.14) 100%)",
    }} />
  </AbsoluteFill>
);

/** The mascot in the corner — the brand's face. Two modes:
 *  - react: a held pose (pose = file stem under public/mascot/)
 *  - speak: cartoon mouth-flaps — `mouth` is the per-frame loudness track
 *    ("0"-"3" per video frame, scripts/lib/mouthtrack.py via the manifest);
 *    the character swaps host_m0..m3 drawings and "acts" louder syllables.
 *  The character BOILS while held (feTurbulence on threes) — a frozen drawing
 *  is the digital tell. */
export const MascotReact: React.FC<{
  pose: string; sceneDur: number; mouth?: string; mouthOffset?: number;
  /** talking-rig file-stem prefix under public/mascot/ (default "host" =
   *  mindwired astro; blackbox robot = "bb_host") */
  rig?: string;
  /** aside mode: stand at the LEFT frame edge at ~half size, presenting a
   *  diagram/photo that fills the rest of the frame (MascotAside scenes — the
   *  anatomy chapters). Same talking/blink/gesture rig, different placement. */
  aside?: boolean;
}> = ({ pose, sceneDur, mouth, mouthOffset = 10, rig = "host", aside = false }) => {
  const frame = useCurrentFrame();
  // --- entrance: slide up into place + squash-and-stretch landing (2026-07-21,
  //     "animations way better") — deterministic, on the spring primitive.
  const entIn = spring({ frame: frame - 2, fps: FPS, config: { damping: 12, stiffness: 130 } });
  const enterY = (1 - entIn) * 96;              // slides up from below
  const si = frame - 9;                         // frames since the landing beat
  // before impact (si<0) the body is stretched as it drops; after, it bounces
  // (a decaying oscillation) — classic squash-and-stretch settle.
  const squash = si >= 0 ? Math.exp(-si / 4.2) * Math.sin(si / 2.1) * 0.17 : 0.20;
  const sqX = 1 - squash, sqY = 1 + squash;
  // --- exit: an anticipation dip, then spring OUT (anticipation sells the pop).
  const exitStart = sceneDur - 13;
  const ant = interpolate(frame, [exitStart, exitStart + 4], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const leave = spring({ frame: frame - (exitStart + 4), fps: FPS, config: { damping: 13, stiffness: 170 } });
  const exitScale = (1 - 0.09 * ant) * (1 - leave);
  const exitY = 14 * ant + leave * 64;
  // idle quantized ON THREES (~10fps) + seeded per-step jitter: a hand-drawn
  // character "boils" in place — smooth sinusoid glide reads as digital
  const step = Math.floor(frame / 3);
  const jit = mulberry32(seedOf(pose) + step);
  // calm idle (Akshay 2026-07-20: wobble was distracting); machines idle
  // calmer than characters
  const calm = rig.startsWith("bb") ? 0.4 : 0.8;
  const bob = (Math.sin(step / 3.6) * 3 + (jit() - 0.5) * 1) * calm;
  const tilt = (Math.sin(step / 5.6) * 0.8 + (jit() - 0.5) * 0.4) * calm;

  // speaking: sample the mouth track (one char per frame; narration starts at
  // LEAD, passed as mouthOffset); hands cycle per phrase (rig v2 gestures)
  let file = pose;
  let state = 0;
  if (mouth && mouth.length > 0) {
    const i = Math.min(Math.max(frame - mouthOffset, 0), mouth.length - 1);
    state = Math.min(3, Math.max(0, Number(mouth[i]) || 0));
    const g = gestureAt(mouth, i, RIG_GESTURES[rig] ?? 3);
    // a blink briefly overrides the mouth frame (~4f) — eyes shut between words
    // reads perfectly natural and needs only one extra asset per gesture body
    file = (RIG_BLINK[rig] && isBlinking(frame, seedOf(pose)))
      ? `${rig}_g${g}_blink` : `${rig}_g${g}_m${state}`;
  }
  // acting: loud syllables push the whole character a touch (head-bob energy,
  // not just a mouth hole) — quantized with the flaps
  const emph = mouth ? 1 + state * 0.008 : 1;
  const uid = `mboil-${seedOf(pose) % 997}`;

  return (
    <div style={{
      position: "absolute",
      ...(aside
        ? { left: 24, bottom: 8, width: 430, height: 470 }
        : { right: 36, bottom: 12, width: 500, height: 530 }),
      transform: `translateY(${enterY + bob + exitY}px) `
        + `scale(${entIn * exitScale * emph}) scaleX(${sqX}) scaleY(${sqY}) `
        + `rotate(${(aside ? -1.5 : -3) + tilt}deg)`,
      transformOrigin: aside ? "bottom left" : "bottom right",
    }}>
      <svg width={0} height={0} style={{ position: "absolute" }}>
        <filter id={uid} x="-4%" y="-4%" width="108%" height="108%">
          <feTurbulence type="turbulence" baseFrequency="0.021" numOctaves={2}
            seed={(seedOf(file) % 90) + (step % 3)} result="t" />
          <feDisplacementMap in="SourceGraphic" in2="t" scale={4}
            xChannelSelector="R" yChannelSelector="G" />
        </filter>
      </svg>
      <Img
        src={staticFile(`mascot/${file}.png`)}
        style={{
          width: "100%", height: "100%", objectFit: "contain",
          filter: `url(#${uid}) drop-shadow(4px 7px 0px rgba(28,26,23,0.18))`,
        }}
      />
    </div>
  );
};

/** Full-screen mascot cutaway ("mascotFull": true) — the character takes over
 *  the frame, zoomed to face scale, and SPEAKS the scene's narration (mouth
 *  track from the manifest). The comedic-aside beat between heavy chapters:
 *  page-turn in, punchy line, gone. Works inside any doc (real-footage docs
 *  included) — the paper takeover reads as the brand's voice interrupting. */
export const MascotZoom: React.FC<{
  sceneDur: number; mouth?: string; mouthOffset?: number;
  cap?: string; accent: string; rig?: string;
}> = ({ sceneDur, mouth, mouthOffset = 10, cap, accent, rig = "host" }) => {
  const frame = useCurrentFrame();
  // entrance: pop in + a gentle squash-settle (subtler than the corner react —
  // this fills the frame). anticipation-dip exit springs him back out.
  const entIn = spring({ frame: frame - 2, fps: FPS, config: { damping: 13, stiffness: 120 } });
  const si = frame - 8;
  const squash = si >= 0 ? Math.exp(-si / 4.5) * Math.sin(si / 2.2) * 0.10 : 0.12;
  const sqX = 1 - squash, sqY = 1 + squash;
  const exitStart = sceneDur - 12;
  const ant = interpolate(frame, [exitStart, exitStart + 4], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const leave = spring({ frame: frame - (exitStart + 4), fps: FPS, config: { damping: 13, stiffness: 160 } });
  const out = (1 - 0.06 * ant) * (1 - leave);
  const step = Math.floor(frame / 3);
  const jit = mulberry32(9091 + step);
  const calm = rig.startsWith("bb") ? 0.35 : 0.7;
  const bob = (Math.sin(step / 3.2) * 5 + (jit() - 0.5) * 1.5) * calm;
  const tilt = (Math.sin(step / 5.1) * 0.7 + (jit() - 0.5) * 0.4) * calm;

  let state = 0;
  let gesture = 0;
  if (mouth && mouth.length > 0) {
    const i = Math.min(Math.max(frame - mouthOffset, 0), mouth.length - 1);
    state = Math.min(3, Math.max(0, Number(mouth[i]) || 0));
    gesture = gestureAt(mouth, i, RIG_GESTURES[rig] ?? 3);
  }
  const emph = 1 + state * 0.006;
  const capIn = interpolate(frame, [8, 22], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  // face-scale zoom: blow the full-body PNG up to ~2.3x screen height and
  // pull it down so the FACE fills the frame. Face height differs per
  // character — the astronauts' faces sit high, the batti bulb's face sits
  // mid-body — so the vertical anchor is per-rig.
  const IMG_H = 2450;
  const FACE_Y: Record<string, number> = { host: 0.29, bb_host: 0.31, db_host: 0.50 };
  const faceY = FACE_Y[rig] ?? 0.30;
  const top = 540 - faceY * IMG_H;
  return (
    <AbsoluteFill style={{ overflow: "hidden" }}>
      <style>{SKETCH_FONT_CSS}</style>
      <Paper />
      <svg width={0} height={0} style={{ position: "absolute" }}>
        <filter id="zoomboil" x="-4%" y="-4%" width="108%" height="108%">
          <feTurbulence type="turbulence" baseFrequency="0.016" numOctaves={2}
            seed={40 + (step % 3)} result="t" />
          <feDisplacementMap in="SourceGraphic" in2="t" scale={5}
            xChannelSelector="R" yChannelSelector="G" />
        </filter>
      </svg>
      <div style={{
        position: "absolute", left: "50%", top: top + bob,
        width: IMG_H, height: IMG_H,
        transform: `translateX(-50%) scale(${(0.82 + 0.18 * entIn) * out * emph}) `
          + `scaleX(${sqX}) scaleY(${sqY}) rotate(${tilt}deg)`,
        transformOrigin: "50% 30%",
      }}>
        <Img
          src={staticFile(`mascot/${
            RIG_BLINK[rig] && isBlinking(frame, 9091)
              ? `${rig}_g${gesture}_blink` : `${rig}_g${gesture}_m${state}`
          }.png`)}
          style={{
            width: "100%", height: "100%", objectFit: "contain",
            filter: "url(#zoomboil) drop-shadow(0px 10px 0px rgba(28,26,23,0.12))",
          }}
        />
      </div>
      {cap && (
        <div style={{
          position: "absolute", left: 0, right: 0, bottom: 44, textAlign: "center",
          opacity: capIn, transform: `translateY(${(1 - capIn) * 16}px) rotate(-0.8deg)`,
          fontFamily: "'Caveat', cursive", fontWeight: 700, fontSize: 84,
          color: INK,
        }}>
          <span style={{
            background: "rgba(244,240,230,0.85)", padding: "0 28px",
            borderRadius: 14, boxShadow: `0 4px 0 ${accent}`,
          }}>
            {cap}
          </span>
        </div>
      )}
    </AbsoluteFill>
  );
};

/** Which rigs ship eyes-closed blink frames (public/mascot/<rig>_g{G}_blink.png,
 *  composited by gen_mascot.build_rig_v2). Gated so rigs without the asset never
 *  request a 404 frame. */
export const RIG_BLINK: Record<string, boolean> = { bb_host: true };

/** Deterministic blink schedule: a ~4-frame blink every 2-4s, first blink and
 *  cadence seeded per character so two mascots never blink in lockstep. A face
 *  that never blinks is the last remaining "digital" tell. */
const isBlinking = (frame: number, seed: number): boolean => {
  const rnd = mulberry32(seed + 1);
  let t = 24 + (seed % 34);                 // first blink, staggered per rig
  while (t <= frame) {
    if (frame >= t && frame < t + 4) return true;
    t += 60 + Math.floor(rnd() * 60) + 4;   // 2-4s gap, then the 4f blink
  }
  return frame >= t && frame < t + 4;
};

/** How many gesture bodies each rig ships (public/mascot/<rig>_g{0..N-1}_m*).
 *  bb_host got 2 extra (shrug, arms-crossed thinking) in the 2026-07-21
 *  anatomy-episode upgrade → 5; the astro host stays at 3. */
export const RIG_GESTURES: Record<string, number> = { host: 3, bb_host: 5 };

/** Gesture index while speaking: the hands change on each new phrase (a
 *  silence -> speech onset in the mouth track), cycling the rig's gesture
 *  bodies — mouth flaps alone read robotic, hands are the acting. */
const gestureAt = (mouth: string, i: number, gestures = 3) => {
  let g = 0;
  for (let k = 1; k <= Math.min(i, mouth.length - 1); k++) {
    if (mouth[k] !== "0" && mouth[k - 1] === "0") g++;
  }
  return g % gestures;
};

/** Point on the boustrophedon scribble at progress p — drives the pencil
 *  cursor that "draws" the reveal (the classic whiteboard retention trick). */
const scribblePoint = (p: number, w: number, h: number, bands: number) => {
  const t = Math.min(Math.max(p, 0), 1) * bands;
  const band = Math.min(bands - 1, Math.floor(t));
  const u = t - band;
  const y = (h / bands) * band + h / bands / 2;
  const x = band % 2 === 0 ? u * w : (1 - u) * w;
  return { x, y };
};

type SketchProps = {
  file: string | null;      // resolved illustration filename (img rotation)
  slug: string;
  cap?: string;
  stat?: string;
  note?: string;            // small handwritten margin annotation
  accent: string;           // channel accent color
  sceneDur: number;
  /** ink-circle highlight drawn at ~55% through the scene: [cx, cy, r] in
   *  illustration coords (0..1180 x 0..760) — direct the viewer's eye. */
  circle?: number[];
};

export const SketchScene: React.FC<SketchProps> = ({
  file, slug, cap, stat, note, accent, sceneDur, circle,
}) => {
  const frame = useCurrentFrame();
  const seed = seedOf(`${slug}:${file ?? "none"}`);
  // line boil ON THREES (~10fps, the hand-animation cadence): cycle turbulence
  // seeds so the static art's line quivers like ink — a frozen drawing is the
  // "digital" tell, per the style research
  const boilSeed = (seed % 90) + Math.floor(frame / 3) % 3;

  const W = 1180, H = 760;
  const bands = 9;
  const path = scribblePath(W, H, bands, seed);
  // draw-on: the marker covers the art in ~1.5s — slow enough to read as a
  // hand actually drawing (the anticipation is the retention hook)
  const REVEAL_END = 46;
  const reveal = interpolate(frame, [2, REVEAL_END], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const dashLen = W * bands * 1.35;
  const pen = scribblePoint(reveal, W, H, bands);

  const capIn = interpolate(frame, [16, 34], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const underline = interpolate(frame, [30, 48], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const statPop = spring({ frame: frame - 24, fps: FPS, config: { damping: 10, stiffness: 130 } });
  // directed camera: slow push INTO the drawing (smooth 30fps against the
  // 10fps boil = the mixed cadence of hand-made animation)
  const push = interpolate(frame, [0, Math.max(sceneDur, 1)], [1.0, 1.045]);
  const drift = interpolate(frame, [0, Math.max(sceneDur, 1)], [0, -10]);

  // ink-circle highlight: draws on at ~55% through the scene
  const circleStart = Math.round(Math.max(sceneDur * 0.55, REVEAL_END + 8));
  const circleT = circle ? interpolate(frame, [circleStart, circleStart + 14], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }) : 0;

  return (
    <AbsoluteFill>
      <style>{SKETCH_FONT_CSS}</style>
      <Paper />
      {file && (
        <div style={{
          position: "absolute", left: "50%", top: 78,
          transform: `translateX(-50%) translateY(${-drift}px) rotate(-0.6deg) scale(${push})`,
          transformOrigin: "center 45%",
        }}>
          <svg width={W} height={H} style={{ overflow: "visible" }}>
            <defs>
              <filter id="boil" x="-4%" y="-4%" width="108%" height="108%">
                <feTurbulence type="turbulence" baseFrequency="0.022" numOctaves={2}
                  seed={boilSeed} result="t" />
                <feDisplacementMap in="SourceGraphic" in2="t" scale={6}
                  xChannelSelector="R" yChannelSelector="G" />
              </filter>
              <mask id="reveal">
                <path d={path} stroke="#fff" strokeWidth={H / bands + 14} fill="none"
                  strokeLinecap="round"
                  strokeDasharray={dashLen}
                  strokeDashoffset={dashLen * (1 - reveal)} />
              </mask>
            </defs>
            {/* illustrations are white->alpha preprocessed (gen_mascot.white_to_alpha)
                so real transparency sits on the paper — no blend-mode tricks */}
            <g mask="url(#reveal)">
              <image
                href={staticFile(`shorts/${slug}/images/${file}`)}
                width={W} height={H} preserveAspectRatio="xMidYMid meet"
                filter="url(#boil)"
              />
            </g>
            {/* the drawing hand: a small ink pencil rides the reveal path */}
            {reveal > 0 && reveal < 1 && (
              <g transform={`translate(${pen.x} ${pen.y}) rotate(-38)`}>
                <line x1={4} y1={-6} x2={30} y2={-46} stroke={INK} strokeWidth={7}
                  strokeLinecap="round" />
                <line x1={9} y1={-14} x2={26} y2={-40} stroke={accent} strokeWidth={3}
                  strokeLinecap="round" />
                <path d="M 4 -6 L -3 4 L 8 1 Z" fill={INK} />
              </g>
            )}
            {/* ink-circle highlight (scene field "circle": [cx,cy,r]) */}
            {circle && circle.length >= 3 && circleT > 0 && (() => {
              const [cx, cy, r] = circle;
              const rng = mulberry32(seed + 77);
              const pts: string[] = [];
              const N = 26;
              for (let i = 0; i <= N; i++) {
                const a = (i / N) * Math.PI * 2 - Math.PI / 3;
                const rr = r * (1 + (rng() - 0.5) * 0.09) * (i === N ? 1.04 : 1);
                pts.push(`${i === 0 ? "M" : "L"} ${cx + Math.cos(a) * rr * 1.15} ${cy + Math.sin(a) * rr}`);
              }
              const d = pts.join(" ");
              const len = 2 * Math.PI * r * 1.2;
              return (
                <path d={d} stroke={accent} strokeWidth={7} fill="none"
                  strokeLinecap="round" opacity={0.9}
                  strokeDasharray={len} strokeDashoffset={len * (1 - circleT)} />
              );
            })()}
          </svg>
        </div>
      )}

      {stat && (
        <div style={{
          position: "absolute", left: 64, top: 44,
          transform: `scale(${statPop}) rotate(-2deg)`, transformOrigin: "top left",
          fontFamily: "'Caveat', cursive", fontWeight: 700, fontSize: 74,
          color: accent, textShadow: "1px 2px 0 rgba(28,26,23,0.15)",
        }}>
          {stat}
        </div>
      )}

      {cap && (
        <div style={{
          position: "absolute", left: 84, bottom: 64, maxWidth: 1100,
          opacity: capIn, transform: `translateY(${(1 - capIn) * 14}px) rotate(-1.1deg)`,
        }}>
          <div style={{
            fontFamily: "'Caveat', cursive", fontWeight: 700,
            fontSize: 72, lineHeight: 1.05, color: INK,
          }}>
            {cap}
          </div>
          <svg width={520} height={16} style={{ display: "block", marginTop: 2 }}>
            <path d="M 4 9 C 120 4, 240 13, 380 8 C 440 6, 490 10, 514 8"
              stroke={accent} strokeWidth={6} fill="none" strokeLinecap="round"
              strokeDasharray={540} strokeDashoffset={540 * (1 - underline)} />
          </svg>
        </div>
      )}

      {note && (
        <div style={{
          position: "absolute", right: 70, top: 60, maxWidth: 360,
          opacity: capIn, transform: "rotate(2.4deg)",
          fontFamily: "'Patrick Hand', cursive", fontSize: 38, lineHeight: 1.15,
          color: "rgba(28,26,23,0.72)",
        }}>
          {note}
        </div>
      )}
    </AbsoluteFill>
  );
};

/** Deterministic torn-paper silhouette: a CSS clip-path polygon jittered along
 *  each edge of a unit rectangle, seeded so the same scene always tears the
 *  same way. Built for DossierScene's newsprint scrap; exported in case a v2
 *  torn-tape/string treatment wants the same shape language. */
export const tornPolygon = (seed: number, segsPerSide = 6, jitter = 0.05) => {
  const rng = mulberry32(seed);
  const pts: [number, number][] = [];
  const j = () => (rng() - 0.5) * jitter * 2;
  for (let i = 0; i <= segsPerSide; i++) pts.push([i / segsPerSide, Math.max(0, j())]);
  for (let i = 1; i <= segsPerSide; i++) pts.push([Math.min(1, 1 + j()), i / segsPerSide]);
  for (let i = 1; i <= segsPerSide; i++) pts.push([1 - i / segsPerSide, Math.min(1, 1 + j())]);
  for (let i = 1; i < segsPerSide; i++) pts.push([Math.max(0, j()), 1 - i / segsPerSide]);
  return `polygon(${pts.map(([x, y]) => `${(x * 100).toFixed(1)}% ${(y * 100).toFixed(1)}%`).join(", ")})`;
};

type DossierProps = {
  /** resolved illustration filename (img-prefix rotation, same convention as
   *  every other scene type — a Gemini-generated halftone cutout, alpha'd via
   *  gen_mascot.white_to_alpha) */
  file: string | null;
  slug: string;
  cap?: string;
  /** short 1-4 word date/name stamp, e.g. "NOV 24 1971" — rendered as real
   *  text, not baked into the generated image (crisper, immune to TTS-in-image
   *  legibility problems). */
  label?: string;
  accent: string;
  sceneDur: number;
  camera?: "push" | "pull" | "drift";
};

/** "Case file" reconstruction beat — the illustrated sibling of ExhibitScene
 *  (DocWide.tsx), for narration beats with ZERO real photo/footage coverage
 *  (an unfilmable moment, an abstraction — see docs/guides/DOSSIER-SCENES.md).
 *  Hand-cut paper-collage register: torn newsprint, masking tape, a
 *  rubber-stamp label. A grimmer, more restrained cousin of the
 *  whiteboard/mascot system in this same file (SketchScene/MascotReact), NOT a
 *  revival of it — no cute character, no springy bounce, a single settle, and
 *  it ALWAYS carries the "RECONSTRUCTION" tag so it can never be mistaken for
 *  a real archival photo (same honesty principle as RadioScene's
 *  ACTUAL/RECREATION labels and ExhibitScene's real-document citations). */
export const DossierScene: React.FC<DossierProps> = ({
  file, slug, cap, label, accent, sceneDur, camera,
}) => {
  const frame = useCurrentFrame();
  const seed = seedOf(`${slug}:${file ?? "none"}:dossier`);

  // Ken Burns — same vocabulary as IllusScene, gentler amplitude: this is a
  // held evidence photo, not a montage pan.
  const move = camera ?? "push";
  const t = interpolate(frame, [0, Math.max(sceneDur, 1)], [0, 1]);
  const ease = t * t * (3 - 2 * t);
  const scale = move === "pull" ? interpolate(ease, [0, 1], [1.06, 1.02])
    : move === "drift" ? 1.03
    : interpolate(ease, [0, 1], [1.02, 1.07]);

  // hero settle: paper dropped onto a table, one decaying wobble — a graver
  // register than MascotReact's cartoon squash-and-stretch bounce.
  const drop = spring({ frame: frame - 4, fps: FPS, config: { damping: 20, stiffness: 100 } });
  const si = frame - 4;
  const wobble = si >= 0 ? Math.exp(-si / 8) * Math.sin(si / 3.6) * 1.6 : 0; // degrees
  const heroIn = interpolate(frame, [0, 14], [0, 1], { extrapolateRight: "clamp" });
  const heroY = (1 - drop) * 50;

  const tapeIn = spring({ frame: frame - 16, fps: FPS, config: { damping: 15 } });
  const stampAt = 26;
  const stampIn = spring({ frame: frame - stampAt, fps: FPS, config: { damping: 11, stiffness: 210 } });
  const capIn = interpolate(frame, [18, 34], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const fadeOut = interpolate(frame, [sceneDur - 10, sceneDur], [1, 0], { extrapolateLeft: "clamp" });

  // typewriter reveal: the caption types on character-by-character (a live
  // cursor, not a static card fading in) — ~27 chars/sec, starting where the
  // old fade-in used to start, so a beat with a caption ALSO reads as "being
  // written," not just "appearing."
  const typeStart = 18;
  const charsPerFrame = 0.9;
  const capLen = cap?.length ?? 0;
  const capChars = Math.max(0, Math.min(capLen, Math.floor((frame - typeStart) * charsPerFrame)));
  const capTyping = capChars < capLen;
  const cursorOn = capTyping && frame % 20 < 10;

  const scrapClip = tornPolygon(seed + 11);
  const scrapRot = -3 + (mulberry32(seed)() - 0.5) * 4;

  return (
    <AbsoluteFill style={{ backgroundColor: "#0C0A08", opacity: fadeOut }}>
      <Paper />
      {/* graver than the whiteboard: heavier vignette + sepia-leaning overlay */}
      <AbsoluteFill style={{
        background: "radial-gradient(ellipse at center, transparent 42%, rgba(18,13,8,0.45) 100%)",
      }} />
      <AbsoluteFill style={{
        background: "linear-gradient(180deg, rgba(10,8,6,0.3) 0%, transparent 22%, transparent 72%, rgba(10,8,6,0.55) 100%)",
        pointerEvents: "none",
      }} />

      {file && (
        <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", opacity: heroIn }}>
          {/* torn newsprint scrap behind the hero cutout */}
          <div style={{
            position: "absolute", width: "58%", height: "68%",
            transform: `rotate(${scrapRot}deg)`,
            background: "#E7DCC4", clipPath: scrapClip,
            boxShadow: "0 22px 60px rgba(0,0,0,0.5)",
          }} />
          {/* hero cutout — contain, never crops a portrait or landscape source */}
          <div style={{
            position: "relative", height: "62%",
            transform: `translateY(${heroY}px) rotate(${wobble}deg) scale(${scale})`,
            filter: "drop-shadow(0 22px 34px rgba(0,0,0,0.55)) saturate(0.82) contrast(1.08)",
          }}>
            <Img src={staticFile(`shorts/${slug}/images/${file}`)}
              style={{ height: "100%", width: "auto", objectFit: "contain", display: "block" }} />
          </div>
          {/* masking-tape corner, pinning the scrap down */}
          <div style={{
            position: "absolute", top: "17%", left: "38%",
            width: 132, height: 42, opacity: tapeIn * 0.82,
            transform: `scale(${tapeIn}) rotate(-9deg)`,
            background: "linear-gradient(180deg, rgba(232,224,198,0.92), rgba(210,200,172,0.85))",
            boxShadow: "0 4px 10px rgba(0,0,0,0.25)",
          }} />
        </AbsoluteFill>
      )}

      {label && (
        <div style={{
          position: "absolute", top: 90, left: 96,
          opacity: stampIn, transform: `scale(${stampIn}) rotate(-5deg)`,
        }}>
          <div style={{
            fontFamily: "'Courier New', monospace", fontWeight: 700, fontSize: 30,
            letterSpacing: 3, color: accent, border: `3px solid ${accent}`,
            padding: "8px 22px", borderRadius: 3,
            boxShadow: `0 0 ${16 + stampIn * 10}px ${accent}55`,
          }}>{label}</div>
        </div>
      )}

      {cap && (
        <div style={{
          position: "absolute", bottom: 96, left: 96, right: 96,
          opacity: capIn, transform: `translateY(${interpolate(capIn, [0, 1], [22, 0])}px)`,
        }}>
          <div style={{
            fontFamily: "'Courier New', monospace", fontWeight: 700, fontSize: 34,
            color: "rgba(244,240,230,0.92)", lineHeight: 1.34,
            textShadow: "0 3px 16px rgba(0,0,0,0.8)",
          }}>
            <span style={{ borderBottom: `3px solid ${accent}`, paddingBottom: 4 }}>
              {cap.slice(0, capChars)}
              {cursorOn && <span style={{ color: accent }}>|</span>}
            </span>
          </div>
        </div>
      )}

      {/* honesty tag — non-optional, never remove: this is an illustrated
          reconstruction, never a real archival photo */}
      <div style={{
        position: "absolute", bottom: 30, right: 44, opacity: 0.6,
        fontFamily: "'Courier New', monospace", fontWeight: 700, fontSize: 17,
        letterSpacing: 3, color: "rgba(244,240,230,0.85)",
      }}>RECONSTRUCTION</div>
    </AbsoluteFill>
  );
};
