/** Hand-drawn illustrated scene layer for the doc engine (2026-07-19).
 *
 *  The anti-"AI slop" brand look: Gemini illustrations in ONE locked ink style
 *  (scripts/gen_mascot.py STYLE) rendered on textured paper with a marker-style
 *  draw-on reveal, subtle line boil, handwritten captions (Caveat), and the
 *  recurring mascot reacting in the corner (public/mascot/<pose>.png,
 *  generated by scripts/gen_mascot.py — the channel's face).
 *
 *  Scene fields (DocWide): sketch:true + img:<prefix> -> SketchScene;
 *  react:<pose> overlays the mascot on ANY scene type.
 */
import React from "react";
import {
  AbsoluteFill, Img, interpolate, spring, staticFile, useCurrentFrame,
} from "remotion";
import { SKETCH_FONT_CSS } from "./sketchFonts";

const FPS = 30;
const PAPER = "#F4F0E6";
const INK = "#1C1A17";

/* deterministic rng (Remotion rule: no bare Math.random) */
const mulberry32 = (a: number) => () => {
  a |= 0; a = (a + 0x6d2b79f5) | 0;
  let t = Math.imul(a ^ (a >>> 15), 1 | a);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const seedOf = (s: string) => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
};

/** Thick boustrophedon scribble path covering a box — used as a mask stroke so
 *  the illustration appears where the "marker" has passed. */
const scribblePath = (w: number, h: number, bands: number, seed: number) => {
  const rng = mulberry32(seed);
  const bh = h / bands;
  let d = `M ${-w * 0.05} ${bh / 2}`;
  for (let i = 0; i < bands; i++) {
    const y = bh * i + bh / 2;
    const wob = () => (rng() - 0.5) * bh * 0.5;
    if (i % 2 === 0) {
      d += ` C ${w * 0.3} ${y + wob()}, ${w * 0.7} ${y + wob()}, ${w * 1.05} ${y}`;
    } else {
      d += ` C ${w * 0.7} ${y + wob()}, ${w * 0.3} ${y + wob()}, ${-w * 0.05} ${y}`;
    }
    if (i < bands - 1) {
      const xEnd = i % 2 === 0 ? w * 1.05 : -w * 0.05;
      d += ` C ${xEnd} ${y + bh * 0.6}, ${xEnd} ${y + bh * 0.9}, ${xEnd} ${y + bh}`;
    }
  }
  return d;
};

/** Paper background: warm tone + procedural grain + soft vignette. */
export const Paper: React.FC = () => (
  <AbsoluteFill style={{ background: PAPER }}>
    <svg width="100%" height="100%" style={{ position: "absolute", opacity: 0.5 }}>
      <filter id="paperGrain">
        <feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves={2} seed={7} />
        <feColorMatrix type="matrix"
          values="0 0 0 0 0.55  0 0 0 0 0.52  0 0 0 0 0.46  0 0 0 0.06 0" />
      </filter>
      <rect width="100%" height="100%" filter="url(#paperGrain)" />
    </svg>
    <AbsoluteFill style={{
      background: "radial-gradient(ellipse at center, transparent 58%, rgba(60,50,30,0.14) 100%)",
    }} />
  </AbsoluteFill>
);

/** The mascot in the corner — the brand's face. Two modes:
 *  - react: a held pose (pose = file stem under public/mascot/)
 *  - speak: cartoon mouth-flaps — `mouth` is the per-frame loudness track
 *    ("0"-"3" per video frame, scripts/lib/mouthtrack.py via the manifest);
 *    the character swaps host_m0..m3 drawings and "acts" louder syllables.
 *  The character BOILS while held (feTurbulence on threes) — a frozen drawing
 *  is the digital tell. */
export const MascotReact: React.FC<{
  pose: string; sceneDur: number; mouth?: string; mouthOffset?: number;
  /** talking-rig file-stem prefix under public/mascot/ (default "host" =
   *  mindwired astro; blackbox robot = "bb_host") */
  rig?: string;
}> = ({ pose, sceneDur, mouth, mouthOffset = 10, rig = "host" }) => {
  const frame = useCurrentFrame();
  const pop = spring({ frame: frame - 4, fps: FPS, config: { damping: 11, stiffness: 140 } });
  const out = interpolate(frame, [sceneDur - 8, sceneDur - 2], [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  // idle quantized ON THREES (~10fps) + seeded per-step jitter: a hand-drawn
  // character "boils" in place — smooth sinusoid glide reads as digital
  const step = Math.floor(frame / 3);
  const jit = mulberry32(seedOf(pose) + step);
  // calm idle (Akshay 2026-07-20: wobble was distracting); machines idle
  // calmer than characters
  const calm = rig.startsWith("bb") ? 0.4 : 0.8;
  const bob = (Math.sin(step / 3.6) * 3 + (jit() - 0.5) * 1) * calm;
  const tilt = (Math.sin(step / 5.6) * 0.8 + (jit() - 0.5) * 0.4) * calm;

  // speaking: sample the mouth track (one char per frame; narration starts at
  // LEAD, passed as mouthOffset); hands cycle per phrase (rig v2 gestures)
  let file = pose;
  let state = 0;
  if (mouth && mouth.length > 0) {
    const i = Math.min(Math.max(frame - mouthOffset, 0), mouth.length - 1);
    state = Math.min(3, Math.max(0, Number(mouth[i]) || 0));
    file = `${rig}_g${gestureAt(mouth, i)}_m${state}`;
  }
  // acting: loud syllables push the whole character a touch (head-bob energy,
  // not just a mouth hole) — quantized with the flaps
  const emph = mouth ? 1 + state * 0.008 : 1;
  const uid = `mboil-${seedOf(pose) % 997}`;

  return (
    <div style={{
      position: "absolute", right: 36, bottom: 12, width: 500, height: 530,
      transform: `scale(${pop * out * emph}) translateY(${bob}px) rotate(${-3 + tilt}deg)`,
      transformOrigin: "bottom right",
    }}>
      <svg width={0} height={0} style={{ position: "absolute" }}>
        <filter id={uid} x="-4%" y="-4%" width="108%" height="108%">
          <feTurbulence type="turbulence" baseFrequency="0.021" numOctaves={2}
            seed={(seedOf(file) % 90) + (step % 3)} result="t" />
          <feDisplacementMap in="SourceGraphic" in2="t" scale={4}
            xChannelSelector="R" yChannelSelector="G" />
        </filter>
      </svg>
      <Img
        src={staticFile(`mascot/${file}.png`)}
        style={{
          width: "100%", height: "100%", objectFit: "contain",
          filter: `url(#${uid}) drop-shadow(4px 7px 0px rgba(28,26,23,0.18))`,
        }}
      />
    </div>
  );
};

/** Full-screen mascot cutaway ("mascotFull": true) — the character takes over
 *  the frame, zoomed to face scale, and SPEAKS the scene's narration (mouth
 *  track from the manifest). The comedic-aside beat between heavy chapters:
 *  page-turn in, punchy line, gone. Works inside any doc (real-footage docs
 *  included) — the paper takeover reads as the brand's voice interrupting. */
export const MascotZoom: React.FC<{
  sceneDur: number; mouth?: string; mouthOffset?: number;
  cap?: string; accent: string; rig?: string;
}> = ({ sceneDur, mouth, mouthOffset = 10, cap, accent, rig = "host" }) => {
  const frame = useCurrentFrame();
  const pop = spring({ frame: frame - 2, fps: FPS, config: { damping: 13, stiffness: 120 } });
  const out = interpolate(frame, [sceneDur - 7, sceneDur - 1], [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const step = Math.floor(frame / 3);
  const jit = mulberry32(9091 + step);
  const calm = rig.startsWith("bb") ? 0.35 : 0.7;
  const bob = (Math.sin(step / 3.2) * 5 + (jit() - 0.5) * 1.5) * calm;
  const tilt = (Math.sin(step / 5.1) * 0.7 + (jit() - 0.5) * 0.4) * calm;

  let state = 0;
  let gesture = 0;
  if (mouth && mouth.length > 0) {
    const i = Math.min(Math.max(frame - mouthOffset, 0), mouth.length - 1);
    state = Math.min(3, Math.max(0, Number(mouth[i]) || 0));
    gesture = gestureAt(mouth, i);
  }
  const emph = 1 + state * 0.006;
  const capIn = interpolate(frame, [8, 22], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  // face-scale zoom: the rig PNGs are full-body with the head in the top ~38%;
  // blowing the image up to ~2.3x screen height and pulling it down centres
  // the face and fills the frame
  const IMG_H = 2450;
  return (
    <AbsoluteFill style={{ overflow: "hidden" }}>
      <style>{SKETCH_FONT_CSS}</style>
      <Paper />
      <svg width={0} height={0} style={{ position: "absolute" }}>
        <filter id="zoomboil" x="-4%" y="-4%" width="108%" height="108%">
          <feTurbulence type="turbulence" baseFrequency="0.016" numOctaves={2}
            seed={40 + (step % 3)} result="t" />
          <feDisplacementMap in="SourceGraphic" in2="t" scale={5}
            xChannelSelector="R" yChannelSelector="G" />
        </filter>
      </svg>
      <div style={{
        position: "absolute", left: "50%", top: -175 + bob,
        width: IMG_H, height: IMG_H,
        transform: `translateX(-50%) scale(${(0.82 + 0.18 * pop) * out * emph}) rotate(${tilt}deg)`,
        transformOrigin: "50% 30%",
      }}>
        <Img
          src={staticFile(`mascot/${rig}_g${gesture}_m${state}.png`)}
          style={{
            width: "100%", height: "100%", objectFit: "contain",
            filter: "url(#zoomboil) drop-shadow(0px 10px 0px rgba(28,26,23,0.12))",
          }}
        />
      </div>
      {cap && (
        <div style={{
          position: "absolute", left: 0, right: 0, bottom: 44, textAlign: "center",
          opacity: capIn, transform: `translateY(${(1 - capIn) * 16}px) rotate(-0.8deg)`,
          fontFamily: "'Caveat', cursive", fontWeight: 700, fontSize: 84,
          color: INK,
        }}>
          <span style={{
            background: "rgba(244,240,230,0.85)", padding: "0 28px",
            borderRadius: 14, boxShadow: `0 4px 0 ${accent}`,
          }}>
            {cap}
          </span>
        </div>
      )}
    </AbsoluteFill>
  );
};

/** Gesture index while speaking: the hands change on each new phrase (a
 *  silence -> speech onset in the mouth track), cycling the rig's 3 gesture
 *  bodies — mouth flaps alone read robotic, hands are the acting. */
const gestureAt = (mouth: string, i: number, gestures = 3) => {
  let g = 0;
  for (let k = 1; k <= Math.min(i, mouth.length - 1); k++) {
    if (mouth[k] !== "0" && mouth[k - 1] === "0") g++;
  }
  return g % gestures;
};

/** Point on the boustrophedon scribble at progress p — drives the pencil
 *  cursor that "draws" the reveal (the classic whiteboard retention trick). */
const scribblePoint = (p: number, w: number, h: number, bands: number) => {
  const t = Math.min(Math.max(p, 0), 1) * bands;
  const band = Math.min(bands - 1, Math.floor(t));
  const u = t - band;
  const y = (h / bands) * band + h / bands / 2;
  const x = band % 2 === 0 ? u * w : (1 - u) * w;
  return { x, y };
};

type SketchProps = {
  file: string | null;      // resolved illustration filename (img rotation)
  slug: string;
  cap?: string;
  stat?: string;
  note?: string;            // small handwritten margin annotation
  accent: string;           // channel accent color
  sceneDur: number;
  /** ink-circle highlight drawn at ~55% through the scene: [cx, cy, r] in
   *  illustration coords (0..1180 x 0..760) — direct the viewer's eye. */
  circle?: number[];
};

export const SketchScene: React.FC<SketchProps> = ({
  file, slug, cap, stat, note, accent, sceneDur, circle,
}) => {
  const frame = useCurrentFrame();
  const seed = seedOf(`${slug}:${file ?? "none"}`);
  // line boil ON THREES (~10fps, the hand-animation cadence): cycle turbulence
  // seeds so the static art's line quivers like ink — a frozen drawing is the
  // "digital" tell, per the style research
  const boilSeed = (seed % 90) + Math.floor(frame / 3) % 3;

  const W = 1180, H = 760;
  const bands = 9;
  const path = scribblePath(W, H, bands, seed);
  // draw-on: the marker covers the art in ~1.5s — slow enough to read as a
  // hand actually drawing (the anticipation is the retention hook)
  const REVEAL_END = 46;
  const reveal = interpolate(frame, [2, REVEAL_END], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const dashLen = W * bands * 1.35;
  const pen = scribblePoint(reveal, W, H, bands);

  const capIn = interpolate(frame, [16, 34], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const underline = interpolate(frame, [30, 48], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const statPop = spring({ frame: frame - 24, fps: FPS, config: { damping: 10, stiffness: 130 } });
  // directed camera: slow push INTO the drawing (smooth 30fps against the
  // 10fps boil = the mixed cadence of hand-made animation)
  const push = interpolate(frame, [0, Math.max(sceneDur, 1)], [1.0, 1.045]);
  const drift = interpolate(frame, [0, Math.max(sceneDur, 1)], [0, -10]);

  // ink-circle highlight: draws on at ~55% through the scene
  const circleStart = Math.round(Math.max(sceneDur * 0.55, REVEAL_END + 8));
  const circleT = circle ? interpolate(frame, [circleStart, circleStart + 14], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }) : 0;

  return (
    <AbsoluteFill>
      <style>{SKETCH_FONT_CSS}</style>
      <Paper />
      {file && (
        <div style={{
          position: "absolute", left: "50%", top: 78,
          transform: `translateX(-50%) translateY(${-drift}px) rotate(-0.6deg) scale(${push})`,
          transformOrigin: "center 45%",
        }}>
          <svg width={W} height={H} style={{ overflow: "visible" }}>
            <defs>
              <filter id="boil" x="-4%" y="-4%" width="108%" height="108%">
                <feTurbulence type="turbulence" baseFrequency="0.022" numOctaves={2}
                  seed={boilSeed} result="t" />
                <feDisplacementMap in="SourceGraphic" in2="t" scale={6}
                  xChannelSelector="R" yChannelSelector="G" />
              </filter>
              <mask id="reveal">
                <path d={path} stroke="#fff" strokeWidth={H / bands + 14} fill="none"
                  strokeLinecap="round"
                  strokeDasharray={dashLen}
                  strokeDashoffset={dashLen * (1 - reveal)} />
              </mask>
            </defs>
            {/* illustrations are white->alpha preprocessed (gen_mascot.white_to_alpha)
                so real transparency sits on the paper — no blend-mode tricks */}
            <g mask="url(#reveal)">
              <image
                href={staticFile(`shorts/${slug}/images/${file}`)}
                width={W} height={H} preserveAspectRatio="xMidYMid meet"
                filter="url(#boil)"
              />
            </g>
            {/* the drawing hand: a small ink pencil rides the reveal path */}
            {reveal > 0 && reveal < 1 && (
              <g transform={`translate(${pen.x} ${pen.y}) rotate(-38)`}>
                <line x1={4} y1={-6} x2={30} y2={-46} stroke={INK} strokeWidth={7}
                  strokeLinecap="round" />
                <line x1={9} y1={-14} x2={26} y2={-40} stroke={accent} strokeWidth={3}
                  strokeLinecap="round" />
                <path d="M 4 -6 L -3 4 L 8 1 Z" fill={INK} />
              </g>
            )}
            {/* ink-circle highlight (scene field "circle": [cx,cy,r]) */}
            {circle && circle.length >= 3 && circleT > 0 && (() => {
              const [cx, cy, r] = circle;
              const rng = mulberry32(seed + 77);
              const pts: string[] = [];
              const N = 26;
              for (let i = 0; i <= N; i++) {
                const a = (i / N) * Math.PI * 2 - Math.PI / 3;
                const rr = r * (1 + (rng() - 0.5) * 0.09) * (i === N ? 1.04 : 1);
                pts.push(`${i === 0 ? "M" : "L"} ${cx + Math.cos(a) * rr * 1.15} ${cy + Math.sin(a) * rr}`);
              }
              const d = pts.join(" ");
              const len = 2 * Math.PI * r * 1.2;
              return (
                <path d={d} stroke={accent} strokeWidth={7} fill="none"
                  strokeLinecap="round" opacity={0.9}
                  strokeDasharray={len} strokeDashoffset={len * (1 - circleT)} />
              );
            })()}
          </svg>
        </div>
      )}

      {stat && (
        <div style={{
          position: "absolute", left: 64, top: 44,
          transform: `scale(${statPop}) rotate(-2deg)`, transformOrigin: "top left",
          fontFamily: "'Caveat', cursive", fontWeight: 700, fontSize: 74,
          color: accent, textShadow: "1px 2px 0 rgba(28,26,23,0.15)",
        }}>
          {stat}
        </div>
      )}

      {cap && (
        <div style={{
          position: "absolute", left: 84, bottom: 64, maxWidth: 1100,
          opacity: capIn, transform: `translateY(${(1 - capIn) * 14}px) rotate(-1.1deg)`,
        }}>
          <div style={{
            fontFamily: "'Caveat', cursive", fontWeight: 700,
            fontSize: 72, lineHeight: 1.05, color: INK,
          }}>
            {cap}
          </div>
          <svg width={520} height={16} style={{ display: "block", marginTop: 2 }}>
            <path d="M 4 9 C 120 4, 240 13, 380 8 C 440 6, 490 10, 514 8"
              stroke={accent} strokeWidth={6} fill="none" strokeLinecap="round"
              strokeDasharray={540} strokeDashoffset={540 * (1 - underline)} />
          </svg>
        </div>
      )}

      {note && (
        <div style={{
          position: "absolute", right: 70, top: 60, maxWidth: 360,
          opacity: capIn, transform: "rotate(2.4deg)",
          fontFamily: "'Patrick Hand', cursive", fontSize: 38, lineHeight: 1.15,
          color: "rgba(28,26,23,0.72)",
        }}>
          {note}
        </div>
      )}
    </AbsoluteFill>
  );
};
